### PR TITLE
CI: Deploy all tagged commits to Github Package Registry

### PR DESCRIPTION
**Pull request by stefan2904**
- New Github Action Workflow to test the project (inspired by the travis config found in the old org-java repo)
- New Github Action Workflow to deploy the project's artifact 
- Adapted Gradle config to use Github Package registry as target for the deployment (instead of oss.sonatype.org).

### CODE REVIEW

**Comment by alensiljak** [comment]
No description?

**Comment by amberin** [comment]
> No description?

@alensiljak Did you mean in the workflow files or in the commit messages?

In any case, good point. But I do think the workflow files are pretty self-explanatory.

**Comment by alensiljak** [comment]
I meant here, in the description. It is not easy to browse through commits or review code on a phone, so having some context would help.

**Comment by stefan2904** [comment]
Sorry, I missed that the commit messages (which explain the PR) did not end up in the description; fixed!

**Comment by alensiljak** [comment]
Thank you!

**Comment by stefan2904** [comment]
if you are happy with the state, could you maybe [tag a release](https://github.com/orgzly-revived/org-java/blob/master/.github/workflows/deploy.yml#L6) so that we can also [adapt the orgzly-revived repo](https://github.com/orgzly-revived/orgzly-android-revived/blob/master/build.gradle#L48) to use this library? Or do you have something different in mind? Thanks a lot! 

I propose 1.3.1 (and also update the [build properties](https://github.com/orgzly-revived/org-java/blob/master/gradle.properties) accordingly).

**Comment by stefan2904** [comment]
Thanks for the release (https://github.com/orgzly-revived/org-java/commit/b148ff226ba3231abe991c3cde15abec79d5d67a)!

**Pull request merged**
